### ISSUE TITLE
Hover inspector UI overflow

### ISSUE THREAD

**Issue by Nekzuris** [openstreetmap/iD#10551]
### URL

https://www.openstreetmap.org/edit#map=18/48.129455/7.827063

### How to reproduce the issue?

Hover over any element.

### Screenshot(s) or anything else?

I found this was caused by `overflow-y: auto;` introduce in #9074 to fix #9070.

current `overflow-y: auto` vs `overflow-y: visible`
![overflow](https://github.com/user-attachments/assets/3b3b1a6c-45d8-467d-a05e-ffa6fba285b6) ![no overflow](https://github.com/user-attachments/assets/9160f39f-5eef-4c03-9ded-36f526c6d360)

I'm not sure what is the best way to fix both, maybe only add scrollbar to notes like this?
```css
.inspector-hover div {
    overflow-x: visible;
    overflow-y: visible;
}
.inspector-hover .comment div {
    overflow-y: auto;
}
```

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome, Firefox
