### ISSUE TITLE
Keep using imagery offset when removing tiles

### ISSUE THREAD

**Issue by hlfan** [openstreetmap/iD#10748]
### URL

https://ideditor.netlify.app/#background=EsriWorldImageryClarity&map=20.40/49.44388/11.08113&offset=1.61,-0.73

### How to reproduce the issue?

1. Have two imagery layers that aren't aligned with each other
Paired with Bing in this case (which the offset is relative to)
2. Switch to second layer
3. See that the outgoing `.tile-removing` tile layer isn't abiding by the specified offset

Another example is at https://ideditor.netlify.app/#background=Bing&map=20.90/48.18559/16.37860&offset=-0.8,-0.54 swapping with Esri.

### Screenshot(s) or anything else?

![Image](https://github.com/user-attachments/assets/ed436d59-4df5-452d-a082-7bb367701fc7)
Slowed down tenfold

Also the `z-index: 1` on `.tile-removing` covers everything else in the SVG, I wrote this CSS patch:
```css
.ideditor :is(.layer-background, .map-in-map-background) .layer {
	img.tile-removing { z-index: 0 }
	&:has(img.tile-removing) img.tile:not(.tile-removing) {z-index: -1 }
}
```

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.31.1, 2.32.0

### Which browsers are you seeing this problem on?

Chrome, Firefox, Microsoft Edge, Safari
