### ISSUE TITLE
"Assumed to be X" strings are not translatable

### ISSUE THREAD

**Issue by Debeet** [openstreetmap/iD#2286]
"Assumed to be Yes" and "Assumed to be No" are not translatable.

**Comment by ImreSamu** [comment]
The `inspector.check.yes`    and   `inspector.check.no`  are still missing from transifex translations.

If the problem exist is it possible to reopen the issue ?

------ my check method -----
in `./dist/locales/en.json`    exist
in `./dist/locales/de.json`    missing    ( after downloading from transifex )
but according to transifex statistics : "German languages 100% translated" ..

My use case :
- I am creating a translation QA tool and  according to my code - 2 expressions are missing compare to english version   - and it is different than  transifex statistics. 
My code compare  `/dist/locales/en.json`  with other languages json file - and analyse the differences .

**Comment by ImreSamu** [comment]
@bhousel 
>2. I don't know why inspector.check.yes and inspector.check.no don't appear in pl.json

maybe in the file [/data/core.yaml](https://github.com/openstreetmap/iD/blob/master/data/core.yaml)     the  `Yes` and `No` should be enclosed in quotes.

now:
```yaml
    edit: Edit feature
    check:
      yes: Yes
      no: No
```

maybe the correct:
```yaml
    edit: Edit feature
    check:
      "yes": "Yes"
      "no": "No"
```

As I see  in the  [/data/presets.yaml](https://github.com/openstreetmap/iD/blob/master/data/presets.yaml) every `yes` and `no`  quoted.
for example 

```yaml
        placeholder: "Contact Line, Electrified Rail..."
        options:
          contact_line: Contact Line
          rail: Electrified Rail
          "yes": Yes (unspecified)
          "no": "No"
```
