### ISSUE TITLE
"Save" button deformation when count span appears

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3803]
Hello.
In some languages, as 'ru' and 'fr', "save" button deforms, when a count-span appears.

![-2](https://cloud.githubusercontent.com/assets/13479292/22362301/5b76ee88-e4ad-11e6-9bdd-316d085b74b2.png)
![-1](https://cloud.githubusercontent.com/assets/13479292/22362216/cb1cdb22-e4ac-11e6-93fb-9fd625cba17a.png)

I'm not a frontend developer, but I tried to do something like this, and It looks fine.
```css
/*button.save.has-count {
    padding: 9px;
}*/

button.save .count {
    display: none;
}

button.save.has-count .count {
    display: block;
    position: absolute;
    top: 5px;
    background: #fff;
    border-color: #fff;
    opacity: 0.5;
    color: #333;
    padding: 10px;
    height: 30px;
    line-height: 12px;
    border-radius: 4px;
    margin: auto;
    margin-left: 9.1%; /*margin-left: 8.3333%;*/
}
```
![default](https://cloud.githubusercontent.com/assets/13479292/22362215/cb19374c-e4ac-11e6-9c20-6b58c022726c.png)
