### ISSUE TITLE
Touchscreen panning became janky

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#7708]
Steps to reproduce:
1. Begin line drawing mode (e.g. press <kbd>2</kbd>)
2. Put finger on touchscreen, and quickly pan a large distance

The map pans one frame then halts, and I have to try again.

Panning a small distance at first will successfully start panning the map, which can then be dragged freely.

Bisect result:
0473243930130d7bd033b345609e887b5d065b89 is the first bad commit

The code changes are exclusive to Safari, so the offending change boils down to this:

```css
.ideditor, .ideditor * {
    /* disable pinch-to-zoom of the UI on touch devices */
    touch-action: pan-x pan-y;
}
```

I can reproduce this in Chrome OS and Chrome for Android, but not in Firefox Preview for Android — making this look like a bug in Chrome.

[screen recording](https://twister.43foldrs.com/2020-06-16-12-05-01_screenRecording.mp4)
