### ISSUE TITLE
iD should make more clear if it intends to do what it says or not

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8402]
Usually when we click on the suggestions we see in e.g.,
![20210314T144037](https://user-images.githubusercontent.com/1230959/111059821-55f4bb00-84d3-11eb-9664-161304d8985c.jpg)
iD then does the work for us.

But apparently here iD is saying we should do it ourselves.

I.e., I was expecting iD to connect the features for me.

Therefore iD should be more clear, saying instead:
- Press here to Connect the features, or
- Please manually Connect the features

And if indeed iD intended to do the work, but something bad happened, then iD should say that too.

**Comment by jidanni** [comment]
OK, it turns out this is trying to say
- Please manually Connect the features

As even though they are all glowing and pulsating, they need to be connected to a fifth feature...

Anyway, iD still needs to say if it is
- Asking for the user to push a button to allow iD to go ahead and do something, or
- Suggesting the user should do something themselves.

Sure, you could say "just look at the color of the text, or if it is a hyperlink."
Well these days all of that is not dependable anymore. Each website uses different CSS.

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/iD/blob/2a5c68aa04cb4279e5af0d24f00bf7ae9b0635dd/data/core.yaml#L1783

and used in few places https://github.com/search?q=repo%3Aopenstreetmap%2FiD+connect_features&type=code

**Comment by matkoniecz** [comment]
if changed, also some other similar would need to be changed

```
      connect_feature:
        title: Connect this feature
      connect_features:
        title: Connect the features
      connect_using_crossing:
        title: Connect using a crossing
      connect_using_ford:
        title: Connect using a ford
      continue_from_start:
        title: Continue drawing from start
      continue_from_end:
        title: Continue drawing from end
      convert_to_line:
        title: Convert this to a line
      convert_to_area:
        title: Convert this to an area
        annotation: Converted an area to a line.
      delete_feature:
        title: Delete this feature
      extract_point:
        title: Extract this point
      ignore_issue:
```

is anyone interested in making PR making such change? It would require checking what else is similar
